id: PC0F7CA8C
initial_creation_type: input
source_metadata:
  title: Nyāyāvatāra with the Nyāyāvatāravivṛti commentary by Siddharṣigaṇin
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Nyāya
  data entry: Piotr Balcerowicz
  contribution to GRETIL: Piotr Balcerowicz
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:03:23.494782'
last_modified_at: '2022-03-09T15:03:23.494794'
